config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'books#top'
  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def top
  end

  def index
    @book = Book.new
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def create
    @book = Book.new(book_params)
    @books = Book.all
    if @book.save
      flash[:create] = "Book was successfully created."
      redirect_to book_path(@book)
    else
      render :index
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:update] = "Book was successfully updated."
      redirect_to book_path(@book)
    else
      render 'edit'
    end
  end

  def destroy
    book = Book.find(params[:id])
    if book.destroy
      flash[:destroy] = "Book was successfully destroyed."
      redirect_to books_path
    end
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<header>
  <h1 class="edit-head">Editing Book</h1>
</header>
<% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<%= form_with model:@book, local:true do |f| %>
<div class="title-box">
  <p class="title-name">Title</p>
  <%= f.text_field :title %>
</div>
<div class="body-box">
  <p class="body-text">Body</p>
  <%= f.text_area :body %>
</div>
<div class="btn">
  <%= f.submit 'Update Book' %>
</div>
<% end %>
<%= link_to "Show", book_path(@book) %>
<%= link_to "Back", books_path %>

app/views/books/index.html.erb
<% if flash[:destroy] %>
  <div class="massege"><p><%= flash[:destroy] %></p></div>
<% end %>
<header>
  <h1 class="headline">Books</h1>
</header>
<table>
  <thead>
    <tr class="table-head">
    <th>Title</th>
    <th>Body</th>
    <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  <% @books.each do |book| %>
    <tr>
      <td>
        <span class="tbody"><%= book.title %></span>
      </td>
      <td>
        <span class="tbody"><%= book.body %></span>
    　 </td>
       <td>
        <%= link_to "Show", book_path(book.id) %>
        <%= link_to "Edit", edit_book_path(book.id) %>
        <%= link_to "Destroy", book_path(book), method: :delete, "data-confirm" => "Are you sure?" %>
      </td>
    </tr>
  <% end %>
  </tbody>

</table>
<h2>New Book</h2>



<%= form_with model:@book, local:true do |f| %>
<% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="title-box">
  <p class="title-name">Title</p>
  <%= f.text_field :title %>
</div>
<div class="body-box">
  <p class="body-text">Body</p>
  <%= f.text_area :body %>
</div>
  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<% if flash[:create] %>
  <div class="massege"><p><%= flash[:create] %></p></div>
<% end %>
<% if flash[:update] %>
  <div class="massege"><p><%= flash[:update] %></p></div>
<% end %>
<p class="show-title">
<b>Title:</b><%= @book.title %>
</p>
<p class="show-body">
<b>Body:</b><%= @book.body %>
</p>
<%= link_to "Edit", edit_book_path(@book) %>
<%= link_to "Back", books_path %>

app/views/books/top.html.erb
<h1 class="jquery">Hello jQuery!</h1>

<h1 class="top-head">ようこそBookersへ!</h1>
<div class="top-main">
  <p><span class="bookers">Bookers</span>では、さまざまな書籍に関すあなたの意見や</p>
  <p>印象を共有し交換することができます</p>
  <div class="start">
    <%= link_to "start", books_path %>
  </div>
 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <div id="container">
      <div id="theTarget">
        <div class="image1"></div>
        <div class="image2"></div>
        <div class="image3"></div>
        <div class="image4"></div>
        <div class="image5"></div>
      </div>
    </div>
  </body>
</html>